### ISSUE TITLE
Matt Cleanup

### ISSUE THREAD

**Issue by MsJennyGiraffe** [MsJennyGiraffe/the_pivot#50]
Fix category dropdown links
-> hard to click on
Fix so we can't checkout without an item
No price anymore so we need change to the cart bid/buyout
-> rewrite order show

**Comment by matthewecampbell** [comment]
Can't get a flash alert to show up when I try to checkout with nothing.

**Comment by MsJennyGiraffe** [comment]
A flash alert would be good, but really we just want to prevent from checking out so we don't have empty orders.
Did you try re-rendering the cart and do a flash.now?
Maybe we should try to redirect them to item index and try to flash a message with something like, "you need to buy an item to checkout"?
